[package]
name = "editor_source_code"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/source_code.rs"

[lints]
workspace = true

[dependencies]
gpui = { workspace = true }
editor_model = { path = "../editor_model" }
editor_outline = { path = "../editor_outline" }
editor_search = { path = "../editor_search" }
syntax_highlighter = { path = "../syntax_highlighter" }
theme = { path = "../theme" }
