[package]
name = "markdown_parser"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[features]
default = ["html-native"]
html-native = ["tree-sitter-html"]

[lints]
workspace = true

[dependencies]
url = "2"
unicode-segmentation = "1.13"
regex = "1.10"
uuid = { workspace = true }
cssparser = "0.37"
tree-sitter = { workspace = true }
tree-sitter-html = { workspace = true, optional = true }
