//! Inline text tree data model and editing operations.
//!
//! [`BlockText`] is a sequence of [`InlineFragment`]s; Markdown markers are
//! parsed by `super::markdown` at the I/O boundary and regenerated by
//! `super::serialize` on save, which keeps editing operations focused on
//! text ranges instead of raw delimiter strings.

use std::ops::Range;

use super::markdown::{NormalizeBuilder, flatten_tokens, parse_until};
use super::serialize::{clamp_to_char_boundary, serialize_fragment_run_with_offset_map};
use crate::block::link::LinkReferenceDefinitions;
use crate::inline::footnote::InlineFootnoteReference;
use crate::inline::html::HtmlInlineStyle;
use crate::inline::latex::InlineLatex;
use crate::inline::link::InlineLink;
use crate::inline::offsets::{InlineEditResult, SourceOffsetMap};
use crate::inline::render_cache::InlineRenderCache;
use crate::inline::style::{InlineStyle, StyleFlag, set_style_flag, style_flag_enabled};

/// Unified set of inline formatting and semantic attributes.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct InlineAttributes {
    pub style: InlineStyle,
    pub html_style: Option<HtmlInlineStyle>,
    pub link: Option<InlineLink>,
    pub footnote: Option<InlineFootnoteReference>,
    pub math: Option<InlineLatex>,
}

impl InlineAttributes {
    pub fn from_fragment(fragment: &InlineFragment) -> Self {
        fragment.attributes()
    }
}

/// A contiguous run of text with uniform [`InlineAttributes`].
///
/// The [`BlockText`] is simply a `Vec<InlineFragment>` with
/// adjacent fragments of equal style merged during normalization.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct InlineFragment {
    pub text: String,
    pub style: InlineStyle,
    pub html_style: Option<HtmlInlineStyle>,
    pub link: Option<InlineLink>,
    pub footnote: Option<InlineFootnoteReference>,
    pub math: Option<InlineLatex>,
}

impl InlineFragment {
    pub fn new(text: impl Into<String>, attrs: InlineAttributes) -> Self {
        Self {
            text: text.into(),
            style: attrs.style,
            html_style: attrs.html_style,
            link: attrs.link,
            footnote: attrs.footnote,
            math: attrs.math,
        }
    }

    pub fn plain(text: impl Into<String>) -> Self {
        Self {
            text: text.into(),
            style: InlineStyle::default(),
            html_style: None,
            link: None,
            footnote: None,
            math: None,
        }
    }

    pub fn attributes(&self) -> InlineAttributes {
        InlineAttributes {
            style: self.style,
            html_style: self.html_style,
            link: self.link.clone(),
            footnote: self.footnote.clone(),
            math: self.math.clone(),
        }
    }

    pub fn with_attributes(text: impl Into<String>, attrs: &InlineAttributes) -> Self {
        Self {
            text: text.into(),
            style: attrs.style,
            html_style: attrs.html_style,
            link: attrs.link.clone(),
            footnote: attrs.footnote.clone(),
            math: attrs.math.clone(),
        }
    }
}

/// Fragment attributes inherited by inserted text at a caret position.
pub type InlineInsertionAttributes = InlineAttributes;

/// A sequence of [`InlineFragment`]s representing inline-formatted text.
///
/// This is the core data structure for block text.  It supports:
/// - Building from raw Markdown (auto-parsing bold/italic/underline markers)
/// - Bidirectional Markdown serialization with optimal delimiter choice
/// - Splitting at arbitrary byte offsets (used for Enter key, paste)
/// - Toggling inline styles on arbitrary ranges
///
/// The serialization uses a Viterbi-like DP optimization to choose between
/// Markdown and HTML delimiter variants, avoiding ambiguous `****` runs.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct BlockText {
    pub fragments: Vec<InlineFragment>,
}

impl BlockText {
    pub fn plain(text: impl Into<String>) -> Self {
        Self::from_fragments(vec![InlineFragment::plain(text)])
    }

    /// Parse marker-based Markdown into the internal fragment representation.
    ///
    /// Markers (`**`, `*`, `<u>`, `<strong>`, `<em>`) are consumed and
    /// converted to [`InlineStyle`] flags on adjacent fragments.  The
    /// markers themselves are never stored — the tree holds only text
    /// content and style attributes.
    pub fn from_markdown(markdown: &str) -> Self {
        Self::from_markdown_with_link_references(markdown, &LinkReferenceDefinitions::default())
    }

    pub fn from_markdown_with_link_references(
        markdown: &str,
        reference_definitions: &LinkReferenceDefinitions,
    ) -> Self {
        let mut tree = Self::plain(markdown)
            .normalize_inline_syntax_with_link_references(reference_definitions)
            .tree;
        tree.normalize_code_spans();
        tree
    }

    /// Code-span content normalization:
    /// - CRLF/CR line endings are normalized to LF so inline code can render
    ///   across hard lines in the editor.
    /// - If the content is not entirely spaces and both starts AND ends with
    ///   a single space, those two spaces are stripped.
    fn normalize_code_spans(&mut self) {
        for fragment in &mut self.fragments {
            if fragment.style.code && !fragment.text.is_empty() {
                let mut s = fragment.text.replace("\r\n", "\n").replace('\r', "\n");
                let all_space = s.chars().all(|c| c == ' ');
                if !all_space && s.starts_with(' ') && s.ends_with(' ') {
                    s.remove(0);
                    s.pop();
                }
                fragment.text = s;
            }
        }
        self.normalize_fragments();
    }

    pub fn from_fragments(fragments: Vec<InlineFragment>) -> Self {
        let mut tree = Self { fragments };
        tree.normalize_fragments();
        tree
    }

    pub fn plain_text(&self) -> String {
        let mut text = String::new();
        for fragment in &self.fragments {
            text.push_str(&fragment.text);
        }
        text
    }

    pub fn plain_len(&self) -> usize {
        self.fragments.iter().map(|f| f.text.len()).sum()
    }

    pub fn has_source_preserving_links(&self) -> bool {
        self.fragments.iter().any(|fragment| {
            fragment
                .link
                .as_ref()
                .is_some_and(InlineLink::is_source_preserving)
                || fragment.footnote.is_some()
                || fragment.math.is_some()
        })
    }

    /// Whether any fragment carries an inline `[label](url)` link. Unlike
    /// reference/autolink links these are not "source preserving", but their
    /// `[...](...)` markers are still stripped from the fragment text, so an
    /// edit that re-derives the tree from plain text alone would drop them.
    pub fn has_inline_links(&self) -> bool {
        self.fragments
            .iter()
            .any(|fragment| matches!(fragment.link, Some(InlineLink::Inline { .. })))
    }

    /// Whether any fragment carries an inline math or script span. These need
    /// the display-only mixed-visual rendering path: math renders as an SVG,
    /// and script (superscript/subscript, footnote references) as smaller text
    /// with a baseline offset — the single-font-size shaped-text editor cannot
    /// express either per run. Once focused the text element takes over for
    /// editing, so both layouts must agree on line height to avoid a jump.
    pub fn has_mixed_inline_visuals(&self) -> bool {
        self.fragments
            .iter()
            .any(|fragment| fragment.math.is_some() || fragment.style.has_script())
    }

    pub fn has_footnote_references(&self) -> bool {
        self.fragments
            .iter()
            .any(|fragment| fragment.footnote.is_some())
    }

    /// Resolves footnote references against the document registry: every
    /// reference renders as its real id (superscript) with the same style,
    /// resolved or not; `resolve` returns the occurrence index when the id
    /// has a definition so jumps can locate the exact reference.
    pub fn apply_footnote_reference_state(
        &mut self,
        mut resolve: impl FnMut(&str) -> Option<usize>,
    ) {
        use crate::inline::style::InlineScript;

        for fragment in &mut self.fragments {
            let Some(footnote) = fragment.footnote.as_mut() else {
                continue;
            };
            footnote.occurrence_index = resolve(&footnote.id).unwrap_or(0);
            fragment.text = footnote.id.clone();
            fragment.style.script = InlineScript::Superscript;
        }
        self.normalize_fragments();
    }

    pub fn render_cache(&self) -> InlineRenderCache {
        InlineRenderCache::from_tree(self)
    }

    /// Serialize fragments back to Markdown text with optimal delimiter choices.
    ///
    /// Each fragment's style flags determine which markers surround its text.
    /// This is the export side of the I/O boundary; the internal fragment
    /// representation never stores raw marker characters.
    pub fn serialize_markdown(&self) -> String {
        self.source_offset_map().source
    }

    pub fn source_offset_map(&self) -> SourceOffsetMap {
        if self.fragments.is_empty() {
            return SourceOffsetMap {
                source: String::new(),
                plain_to_source: vec![0],
                source_to_plain: vec![0],
            };
        }

        let mut output = String::new();
        let mut plain_to_source = vec![0; self.plain_len() + 1];
        let mut source_to_plain = vec![0];
        let mut plain_cursor = 0usize;
        let mut index = 0usize;
        while index < self.fragments.len() {
            if let Some(footnote) = self.fragments[index].footnote.clone() {
                let raw_markdown = footnote.raw_markdown();
                let raw_len = raw_markdown.len();
                let run_plain_len = self.fragments[index].text.len();
                let run_start = output.len();
                output.push_str(&raw_markdown);
                let run_end = output.len();

                for local_plain in 0..=run_plain_len {
                    let mapped = if run_plain_len == 0 {
                        0
                    } else {
                        (raw_len * local_plain) / run_plain_len
                    };
                    plain_to_source[plain_cursor + local_plain] = run_start + mapped;
                }

                source_to_plain.resize(run_end + 1, plain_cursor);
                for local_source in 0..=raw_len {
                    let mapped = if raw_len == 0 {
                        0
                    } else {
                        (run_plain_len * local_source) / raw_len
                    };
                    source_to_plain[run_start + local_source] = plain_cursor + mapped;
                }

                plain_cursor += run_plain_len;
                index += 1;
                continue;
            }

            if let Some(math) = self.fragments[index].math.clone() {
                let raw_markdown = math.source;
                let raw_len = raw_markdown.len();
                let run_plain_len = self.fragments[index].text.len();
                let run_start = output.len();
                output.push_str(&raw_markdown);
                let run_end = output.len();

                for local_plain in 0..=run_plain_len {
                    plain_to_source[plain_cursor + local_plain] =
                        run_start + local_plain.min(raw_len);
                }

                source_to_plain.resize(run_end + 1, plain_cursor);
                for local_source in 0..=raw_len {
                    source_to_plain[run_start + local_source] =
                        plain_cursor + local_source.min(run_plain_len);
                }

                plain_cursor += run_plain_len;
                index += 1;
                continue;
            }

            let link = self.fragments[index].link.clone();
            let mut end = index + 1;
            while end < self.fragments.len()
                && self.fragments[end].link == link
                && self.fragments[end].footnote.is_none()
                && self.fragments[end].math.is_none()
            {
                end += 1;
            }

            let run_map = serialize_fragment_run_with_offset_map(&self.fragments[index..end]);
            if let Some(link) = link {
                let run_plain_len = run_map.plain_to_source.len().saturating_sub(1);
                let link_start = output.len();
                let editable_text = link.editable_text();
                output.push_str(link.open_marker());
                output.push_str(run_map.source());
                if let Some(middle_marker) = link.middle_marker() {
                    output.push_str(middle_marker);
                }
                if let Some(editable_text) = editable_text.as_deref() {
                    output.push_str(editable_text);
                }
                output.push_str(link.close_marker());
                let link_end = output.len();
                let label_source_start = link_start + link.open_marker().len();

                for local_plain in 0..=run_plain_len {
                    plain_to_source[plain_cursor + local_plain] =
                        label_source_start + run_map.plain_to_source_offset(local_plain);
                }

                source_to_plain.resize(link_end + 1, plain_cursor);
                for local in 0..=link.open_marker().len() {
                    source_to_plain[link_start + local] = plain_cursor;
                }
                for local_source in 0..run_map.source().len() {
                    source_to_plain[label_source_start + local_source] =
                        plain_cursor + run_map.source_to_plain_offset(local_source);
                }

                let label_source_end = label_source_start + run_map.source().len();
                source_to_plain[label_source_end] = plain_cursor + run_plain_len;
                for local in 0..=link.close_marker().len() {
                    source_to_plain[link_end.saturating_sub(local)] = plain_cursor + run_plain_len;
                }

                plain_cursor += run_plain_len;
            } else {
                let run_start = output.len();
                output.push_str(run_map.source());
                let run_end = output.len();

                let run_plain_len = run_map.plain_to_source.len().saturating_sub(1);
                for local_plain in 0..=run_plain_len {
                    plain_to_source[plain_cursor + local_plain] =
                        run_start + run_map.plain_to_source_offset(local_plain);
                }

                source_to_plain.resize(run_end + 1, plain_cursor);
                for local_source in 0..=run_map.source().len() {
                    source_to_plain[run_start + local_source] =
                        plain_cursor + run_map.source_to_plain_offset(local_source);
                }
                plain_cursor += run_plain_len;
            }

            index = end;
        }

        SourceOffsetMap {
            source: output,
            plain_to_source,
            source_to_plain,
        }
    }

    pub fn split_at(&self, offset: usize) -> (Self, Self) {
        let clamped = offset.min(self.plain_len());
        let mut left = Vec::new();
        let mut right = Vec::new();
        let mut consumed = 0;

        for fragment in &self.fragments {
            let fragment_len = fragment.text.len();
            let fragment_start = consumed;
            let fragment_end = fragment_start + fragment_len;

            if clamped <= fragment_start {
                right.push(fragment.clone());
            } else if clamped >= fragment_end {
                left.push(fragment.clone());
            } else {
                let split_offset = clamp_to_char_boundary(&fragment.text, clamped - fragment_start);
                let mut attrs = fragment.attributes();
                attrs.math = None;
                if split_offset > 0 {
                    left.push(InlineFragment::with_attributes(
                        &fragment.text[..split_offset],
                        &attrs,
                    ));
                }
                if split_offset < fragment_len {
                    right.push(InlineFragment::with_attributes(
                        &fragment.text[split_offset..],
                        &attrs,
                    ));
                }
            }

            consumed = fragment_end;
        }

        (Self::from_fragments(left), Self::from_fragments(right))
    }

    pub fn append(&mut self, other: Self) {
        self.fragments.extend(other.fragments);
        self.normalize_fragments();
    }

    pub fn replace_fragment_range(
        &mut self,
        range: Range<usize>,
        replacement: Vec<InlineFragment>,
    ) {
        self.fragments.splice(range, replacement);
        self.normalize_fragments();
    }

    pub fn remove_plain_prefix(&mut self, prefix_len: usize) {
        let (_, tail) = self.split_at(prefix_len);
        *self = tail;
    }

    pub fn attributes_for_insertion_at(&self, offset: usize) -> InlineInsertionAttributes {
        if self.fragments.is_empty() {
            return InlineInsertionAttributes::default();
        }

        let clamped = offset.min(self.plain_len());
        let mut consumed = 0;

        for (index, fragment) in self.fragments.iter().enumerate() {
            let fragment_len = fragment.text.len();
            let fragment_start = consumed;
            let fragment_end = fragment_start + fragment_len;

            let mut attrs = fragment.attributes();
            attrs.math = None;

            if fragment_start < clamped && clamped < fragment_end {
                return attrs;
            }

            // Typing at a delimited-fragment boundary should produce plain
            // text, not extend the span past its visible closing/opening
            // marker when the caret is outside.
            if clamped == fragment_end && index + 1 == self.fragments.len() {
                return if fragment.style.code || fragment.style.strikethrough {
                    InlineInsertionAttributes::default()
                } else {
                    attrs
                };
            }

            if clamped == fragment_start && index == 0 {
                return if fragment.style.code || fragment.style.strikethrough {
                    InlineInsertionAttributes::default()
                } else {
                    attrs
                };
            }

            consumed = fragment_end;
        }

        InlineInsertionAttributes::default()
    }

    pub fn toggle_bold(&mut self, range: Range<usize>) -> bool {
        self.toggle_style(range, StyleFlag::Bold)
    }

    pub fn toggle_italic(&mut self, range: Range<usize>) -> bool {
        self.toggle_style(range, StyleFlag::Italic)
    }

    pub fn toggle_underline(&mut self, range: Range<usize>) -> bool {
        self.toggle_style(range, StyleFlag::Underline)
    }

    pub fn toggle_code(&mut self, range: Range<usize>) -> bool {
        self.toggle_style(range, StyleFlag::Code)
    }

    pub fn toggle_strikethrough(&mut self, range: Range<usize>) -> bool {
        self.toggle_style(range, StyleFlag::Strikethrough)
    }

    pub fn unwrap_styles_on_fragments(&mut self, targets: &[(usize, StyleFlag)]) {
        if targets.is_empty() {
            return;
        }

        for (fragment_index, flag) in targets {
            if let Some(fragment) = self.fragments.get_mut(*fragment_index) {
                fragment.style = set_style_flag(fragment.style, *flag, false);
            }
        }
        self.normalize_fragments();
    }

    pub fn replace_plain_range_with_link_references(
        &self,
        range: Range<usize>,
        new_text: &str,
        inserted_attributes: InlineInsertionAttributes,
        reference_definitions: &LinkReferenceDefinitions,
    ) -> InlineEditResult {
        let clamped_start = range.start.min(self.plain_len());
        let clamped_end = range.end.min(self.plain_len());
        let (before, tail) = self.split_at(clamped_start);
        let (_, after) = tail.split_at(clamped_end.saturating_sub(clamped_start));

        let mut temp = before;
        if !new_text.is_empty() {
            temp.fragments.push(InlineFragment {
                text: new_text.to_string(),
                style: inserted_attributes.style,
                html_style: inserted_attributes.html_style,
                link: inserted_attributes.link,
                footnote: inserted_attributes.footnote,
                math: inserted_attributes.math,
            });
        }
        temp.append(after);
        temp.normalize_fragments();
        temp.normalize_inline_syntax_with_link_references(reference_definitions)
    }

    /// Like `replace_plain_range_with_link_references` but skips marker
    /// normalization so that backticks, stars, and other delimiters are
    /// stored as-is. Used for verbatim editing where the text must remain
    /// source text.
    pub fn replace_plain_range_verbatim(
        &self,
        range: Range<usize>,
        new_text: &str,
        inserted_attributes: InlineInsertionAttributes,
    ) -> InlineEditResult {
        let clamped_start = range.start.min(self.plain_len());
        let clamped_end = range.end.min(self.plain_len());
        let (before, tail) = self.split_at(clamped_start);
        let (_, after) = tail.split_at(clamped_end.saturating_sub(clamped_start));

        let mut temp = before;
        if !new_text.is_empty() {
            temp.fragments.push(InlineFragment {
                text: new_text.to_string(),
                style: inserted_attributes.style,
                html_style: inserted_attributes.html_style,
                link: inserted_attributes.link,
                footnote: inserted_attributes.footnote,
                math: inserted_attributes.math,
            });
        }
        temp.append(after);
        temp.normalize_fragments();
        let len = temp.plain_len();
        InlineEditResult {
            tree: BlockText::from_fragments(temp.fragments),
            visible_to_normalized: (0..=len).collect(),
        }
    }

    /// Core marker-to-style normalizer: scans the fragment text for
    /// delimiter sequences (`**`, `*`, `<u>`, etc.), removes them, and
    /// applies the corresponding [`InlineStyle`] to the text between
    /// matching pairs.  Unmatched delimiters are emitted as literal text.
    pub fn normalize_inline_syntax_with_link_references(
        &self,
        reference_definitions: &LinkReferenceDefinitions,
    ) -> InlineEditResult {
        let plain_text = self.plain_text();
        let tokens = flatten_tokens(&self.fragments);
        let mut builder = NormalizeBuilder::new(plain_text.len());
        let _ = parse_until(
            &tokens,
            0,
            None,
            InlineStyle::default(),
            None,
            &mut builder,
            false,
            reference_definitions,
        );
        InlineEditResult {
            tree: BlockText::from_fragments(builder.fragments),
            visible_to_normalized: builder.visible_to_normalized,
        }
    }

    fn toggle_style(&mut self, range: Range<usize>, flag: StyleFlag) -> bool {
        if range.is_empty() {
            return false;
        }

        let clamped_start = range.start.min(self.plain_len());
        let clamped_end = range.end.min(self.plain_len());
        if clamped_start >= clamped_end {
            return false;
        }

        let (before, tail) = self.split_at(clamped_start);
        let (mut middle, after) = tail.split_at(clamped_end - clamped_start);
        let should_remove = middle
            .fragments
            .iter()
            .all(|fragment| style_flag_enabled(fragment.style, flag));

        for fragment in &mut middle.fragments {
            fragment.style = set_style_flag(fragment.style, flag, !should_remove);
        }
        middle.normalize_fragments();

        let mut next = before;
        next.append(middle);
        next.append(after);
        *self = next;
        true
    }

    fn normalize_fragments(&mut self) {
        let mut normalized: Vec<InlineFragment> = Vec::new();
        for fragment in self.fragments.drain(..) {
            if fragment.text.is_empty() {
                continue;
            }

            if let Some(last) = normalized.last_mut()
                && last.style == fragment.style
                && last.html_style == fragment.html_style
                && last.link == fragment.link
                && last.footnote == fragment.footnote
                && last.math.is_none()
                && fragment.math.is_none()
            {
                last.text.push_str(&fragment.text);
                continue;
            }

            normalized.push(fragment);
        }
        self.fragments = normalized;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_toggle_strikethrough() {
        let mut text = BlockText::plain("hello world".to_string());
        assert!(text.toggle_strikethrough(0..5));
        assert!(text.fragments[0].style.strikethrough);
        assert_eq!(text.fragments[0].text, "hello");
        assert!(!text.fragments[1].style.strikethrough);
        assert_eq!(text.fragments[1].text, " world");

        // Toggling again removes strikethrough
        assert!(text.toggle_strikethrough(0..5));
        assert!(!text.fragments[0].style.strikethrough);
    }
}
