[package]
name = "editor_search"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/search.rs"

[lints]
workspace = true

[dependencies]
gpui = { workspace = true }
regex = "1.10"
theme = { path = "../theme" }
uuid = { workspace = true }
