[package]
name = "splitype-model"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = ["html-native"]
html-native = ["dep:tree-sitter", "dep:tree-sitter-html"]

[dependencies]
cssparser = { workspace = true }
uuid = { workspace = true }
tree-sitter = { workspace = true, optional = true }
tree-sitter-html = { workspace = true, optional = true }
