[package]
name = "latex"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
primitives = { path = "../primitives" }
markdown = { path = "../markdown" }
gpui = { workspace = true }
ratex-parser = "0.1.13"
ratex-layout = "0.1.13"
ratex-svg = "0.1.13"

directories = "6"
anyhow = { workspace = true }
