[package]
name = "wysiwyg"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
gpui = { workspace = true }
theme = { workspace = true }
editor_contracts = { workspace = true }
platform_contracts = { workspace = true }
markdown_parser = { workspace = true }
syntax_highlighter = { workspace = true }
config = { workspace = true }
ui = { workspace = true }
serde = { workspace = true }
url = "2"
unicode-segmentation = "1.13"
uuid = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
reqwest = { version = "0.13", default-features = false, features = ["blocking", "default-tls"] }
tracing = { workspace = true }

[dev-dependencies]
toml = { workspace = true }

