[package]
name = "ui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
splitter = { path = "../splitter" }
theme = { path = "../theme" }
config = { path = "../config" }
gpui = { workspace = true }
