[package]
name = "source_code"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/source_code.rs"

[lints]
workspace = true

[dependencies]
gpui = { workspace = true }
editor_contracts = { path = "../editor_contracts" }
ui = { path = "../ui" }
syntax_highlighter = { path = "../syntax_highlighter" }
theme = { path = "../theme" }
