[package]
name = "app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
default-run = "app"

[lints]
workspace = true

[features]
default = []

[[bin]]
name = "app"
path = "src/main.rs"

[dependencies]
splitter = { workspace = true }
theme = { workspace = true }
config = { workspace = true }
splitype_installer = { workspace = true }
ui = { workspace = true }
window = { workspace = true }
core_contracts = { workspace = true }
editor = { workspace = true }
pane_wysiwyg = { workspace = true }
pane_source_code = { workspace = true }
pane_preview = { workspace = true }
settings = { workspace = true }
syntax_highlighter = { workspace = true }
splitype_cli = { workspace = true }
explorer = { workspace = true }

gpui = { workspace = true }
gpui_platform = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = "1"
anyhow = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
futures = "0.3"
schemars = "1"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61", features = ["Win32_Storage_FileSystem"] }

[build-dependencies]
embed-resource = "3"
