[package]
name = "editor_builder"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
gpui = { workspace = true }
editor_model = { path = "../editor_model" }
editor_core = { path = "../editor_core" }
editor_wysiwyg = { path = "../editor_wysiwyg" }
editor_source_code = { path = "../editor_source_code" }
editor_preview = { path = "../editor_preview" }
workspace = { path = "../workspace" }
