[package]
name = "editor_contracts"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
rope = { workspace = true }
platform_contracts = { path = "../platform_contracts" }
splitter = { path = "../splitter" }
config = { path = "../config" }
gpui = { workspace = true }
markdown_parser = { path = "../markdown_parser" }
theme = { path = "../theme" }
regex = "1.10"
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

