[package]
name = "editor_contracts"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
rope = { workspace = true }
platform_contracts = { workspace = true }
splitter = { workspace = true }
gpui = { workspace = true }
markdown_parser = { workspace = true }
theme = { workspace = true }
regex = "1.10"
uuid = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

