[package]
name = "mermaid"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
primitives = { path = "../primitives" }
markdown = { path = "../markdown" }
gpui = { workspace = true }
mermaid-rs-renderer = "0.3"

directories = "6"
anyhow = { workspace = true }
