//! Block-editing action definitions — the block-editing action protocol.

use gpui::*;

actions!(
    splitype,
    [
        Newline,
        DeleteBackward,
        Delete,
        WordDeleteBackward,
        WordDeleteForward,
        FocusPrevious,
        FocusNext,
        MoveLeft,
        MoveRight,
        WordMoveLeft,
        WordMoveRight,
        Home,
        End,
        BlockUp,
        BlockDown,
        PageUp,
        PageDown,
        JumpToTop,
        JumpToBottom,
        SelectLeft,
        SelectRight,
        WordSelectLeft,
        WordSelectRight,
        SelectHome,
        SelectEnd,
        SelectAll,
        Undo,
        Redo,
        BoldSelection,
        ItalicSelection,
        UnderlineSelection,
        CodeSelection,
        StrikethroughSelection,
        IndentBlock,
        OutdentBlock,
        ExitCodeBlock,
    ]
);
