[package]
name = "editor_outline"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/outline.rs"

[lints]
workspace = true

[dependencies]
editor = { path = "../editor" }
gpui = { workspace = true }
theme = { path = "../theme" }
