[package]
name = "editor_model"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/editor.rs"

[lints]
workspace = true

[dependencies]
editor_outline = { path = "../editor_outline" }
gpui = { workspace = true }
splitter = { path = "../splitter" }
workspace = { path = "../workspace" }
