[package]
name = "editor"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
rope = { workspace = true }
anyhow = { workspace = true }
config = { workspace = true }
editor_contracts = { workspace = true }
platform_contracts = { workspace = true }
futures = { workspace = true }
gpui = { workspace = true }
markdown_parser = { workspace = true }
syntax_highlighter = { workspace = true }
splitter = { workspace = true }
theme = { workspace = true }
ui = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
toml = { workspace = true }

