[package]
name = "editor"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
config = { path = "../config" }
editor_contracts = { path = "../editor_contracts" }
platform_contracts = { path = "../platform_contracts" }
futures = "0.3"
gpui = { workspace = true }
splitter = { path = "../splitter" }
theme = { path = "../theme" }
ui = { path = "../ui" }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = "0.1"

[dev-dependencies]
toml = "1"

